/**
 * Master QC Module Registry
 *
 * DEVELOPMENT / AI CONTEXT
 * ------------------------
 * This file is the central map of the ACTIVE application architecture.
 * Do not treat an individual application file as standalone when making
 * changes. Use this registry to understand the surrounding ecosystem and
 * inspect related files before changing an interface or shared behavior.
 *
 * ACTIVE APPLICATION FLOW
 *
 *   index.html
 *      |
 *      +--> Eruda (development debugger; intentionally retained)
 *      |
 *      +--> framework-style.css
 *      |
 *      +--> framework-engine.js
 *      |
 *      +--> this registry
 *               |
 *               +--> registered module script
 *                         |
 *                         +--> module object
 *
 * IMPORTANT ACTIVE FILE RELATIONSHIPS
 *
 *   index.html
 *     - Application shell and startup logic.
 *     - Loads the framework, this registry, and development debugger.
 *     - Reads QC_MODULES and dynamically loads each registered module.
 *     - Uses each entry's objectName to obtain the module object.
 *
 *   framework-engine.js
 *     - Provides QCLabFramework.
 *     - Mounts and renders registered modules.
 *     - Owns framework modes, fields, steps, state, and result display.
 *     - Its expectations define the interface that registered modules must
 *       satisfy.
 *
 *   framework-style.css
 *     - Styles the UI generated by framework-engine.js.
 *     - Changes to framework-generated class names or structure may require
 *       corresponding CSS changes.
 *
 *   modules/registry.js (THIS FILE)
 *     - Defines the modules available to the application.
 *     - Connects each module script to the object it exposes.
 *     - Serves as the central development-time map of the active ecosystem.
 *
 *   modules/gmb-core-density.js
 *     - Current implementation of the registered GMB Core Density module.
 *     - Must remain compatible with the module interface expected by
 *       framework-engine.js.
 *
 * MODULE REGISTRATION CONTRACT
 *
 * Each registry entry provides:
 *   - id         : stable module identifier
 *   - title      : display name shown by the application
 *   - script     : module script loaded by index.html
 *   - objectName : global module object expected after the script loads
 *
 * The registered module's fields, steps, and compute() behavior must match
 * the current expectations of framework-engine.js. Before changing either
 * side of that interface, inspect both sides together.
 *
 * DEVELOPMENT NOTES
 *
 * - The ?v=... suffix on module scripts is intentional cache-busting.
 *   Update it when a module needs to be force-refreshed by the browser.
 * - Eruda is intentionally part of the development environment. Do not
 *   remove it as cleanup unless explicitly requested.
 * - This comment is intentionally kept here during development so an AI
 *   working from a single project file has a chance to recognize that the
 *   file belongs to a larger connected system.
 *
 * Before modifying a registered module or framework component:
 *   1. Check this map.
 *   2. Inspect the related active files identified above.
 *   3. Preserve the existing interfaces unless an architectural change is
 *      intentional.
 *   4. Verify that changes remain compatible across the dependency chain.
 *
 * Append ?v=1.0.X to force browsers to fetch updated code immediately.
 */
window.QC_MODULES = [
  {
    id: "gmb_core_density",
    title: "AASHTO T 166 (Core Gmb)",
    script: "modules/gmb-core-density.js?v=1.0.2",
    objectName: "gmbCoreDensityModule"
  }
];
