/**
 * Master QC Module Registry
 *
 * DEVELOPMENT / AI CONTEXT
 * ------------------------
 * This file is the central map of the ACTIVE application architecture.
 * Do not treat an individual application file as standalone when making
 * changes. Use this registry to understand the surrounding ecosystem and
 * inspect related files before changing an interface or shared behavior.
 *
 * ACTIVE APPLICATION FLOW
 *
 *   index.html
 *      |
 *      +--> Eruda (development debugger; intentionally retained)
 *      |
 *      +--> framework-style.css
 *      |
 *      +--> framework-engine.js
 *      |
 *      +--> this registry
 *               |
 *               +--> registered module script
 *                         |
 *                         +--> module object
 *
 * IMPORTANT ACTIVE FILE RELATIONSHIPS
 *
 *   index.html
 *     - Application shell, navigation, and startup logic.
 *     - Loads the framework, this registry, and development debugger.
 *     - Reads QC_MODULES and dynamically loads each registered module.
 *     - Uses registry metadata to construct the navigation tree.
 *     - Uses each entry's objectName to obtain the module object.
 *
 *   framework-engine.js
 *     - Provides QCLabFramework.
 *     - Mounts and renders registered modules.
 *     - Owns framework modes, fields, steps, state, and result display.
 *     - Its expectations define the interface that registered modules must
 *       satisfy.
 *
 *   framework-style.css
 *     - Styles the UI generated by framework-engine.js and the application
 *       navigation.
 *     - Changes to generated class names or structure may require CSS changes.
 *
 *   modules/registry.js (THIS FILE)
 *     - Defines the modules available to the application.
 *     - Defines navigation metadata used to organize those modules.
 *     - Connects each module script to the object it exposes.
 *     - Serves as the central development-time map of the active ecosystem.
 *
 *   modules/gmb-core-density.js
 *     - Current implementation of the registered GMB Core Density module.
 *     - Contains procedure and step metadata as well as its calculation logic.
 *     - Must remain compatible with the module interface expected by
 *       framework-engine.js.
 *
 * NAVIGATION / METADATA MODEL
 *
 * The registry is the source of truth for WHAT exists. Navigation is a
 * rendered view of that information rather than a second hard-coded module
 * list.
 *
 * Registry metadata describes:
 *   - section       : broad navigation area such as testing/reference
 *   - category      : logical grouping inside a section
 *   - procedure     : parent procedure/test that owns a module
 *   - sequence      : ordering within the relevant hierarchy
 *   - parent        : optional parent node for future deeper hierarchies
 *
 * Procedure/module files can additionally describe step-level relationships
 * such as requires, supports, and follows. Those relationships are useful
 * for future workflow/graph views; they are not required to be tree-shaped.
 *
 * IMPORTANT:
 *   A navigation tree is a VIEW of the metadata. Do not duplicate the same
 *   procedure or module just to make it appear in another navigation view.
 *   Future views may project the same metadata differently (for example,
 *   technician workday order versus laboratory testing order).
 *
 * MODULE REGISTRATION CONTRACT
 *
 * Each registry entry provides:
 *   - id         : stable module identifier
 *   - title      : display name
 *   - file       : module script loaded by index.html
 *   - objectName : global module object expected after the script loads
 *   - navigation : metadata used to place the module in navigation
 *
 * The registered module's fields, steps, and compute() behavior must match
 * the current expectations of framework-engine.js. Before changing either
 * side of that interface, inspect both sides together.
 *
 * DEVELOPMENT NOTES
 *
 * - The ?v=... suffix on module scripts is intentional cache-busting.
 *   Update it when a module needs to be force-refreshed by the browser.
 * - Eruda is intentionally part of the development environment. Do not
 *   remove it as cleanup unless explicitly requested.
 * - This comment is intentionally kept here during development so an AI
 *   working from a single project file has a chance to recognize that the
 *   file belongs to a larger connected system.
 *
 * Before modifying a registered module or framework component:
 *   1. Check this map.
 *   2. Inspect the related active files identified above.
 *   3. Preserve the existing interfaces unless an architectural change is
 *      intentional.
 *   4. Verify that changes remain compatible across the dependency chain.
 *
 * Append ?v=1.0.X to force browsers to fetch updated code immediately.
 */

// The registry does not contain the procedure math itself. It is the application's index:
// "what modules exist, where their files are, and where they belong in navigation/workflow."
window.QC_MODULES = [
  {
    id: "gmb_core_prep",
    title: "Field Core Drilling & Prep",
    file: "modules/gmb-core-prep.js?v=1.0.1",
    objectName: "gmbCorePrepModule",

    // Standard Lab Hierarchy Navigation
    navigation: {
      section: "testing",
      category: "field_sampling",
      categoryTitle: "Field Sampling & Prep",
      procedure: "core_prep",
      procedureTitle: "Core Extraction",
      sequence: 5
    },

    // Workday Workflow & Data Ordering
    workflow: {
      prequels: [],
      sequels: ["gmb_core_density"],
      chronologicalOrder: 10
    }
  },
  {
    id: "gmb_core_density",
    title: "AASHTO T 166 (Core Gmb)",
    file: "modules/gmb-core-density.js?v=1.0.3",
    objectName: "gmbCoreDensityModule",

    // Standard Lab Hierarchy Navigation
    navigation: {
      section: "testing",
      category: "volumetric_properties",
      categoryTitle: "Volumetric Properties",
      procedure: "aashto_t166",
      procedureTitle: "AASHTO T 166",
      sequence: 10
    },

    // Workday Workflow & Data Ordering
    workflow: {
      prequels: ["gmb_core_prep"],
      sequels: [],
      chronologicalOrder: 30
    }
  }
];

// Application-level navigation sections
// Navigation sections describe the different ways the same module metadata can be viewed.
// The Workday section uses workflow.chronologicalOrder; Testing uses navigation metadata.
window.QC_NAVIGATION = {
  sections: [
    {
      id: "workday",
      title: "Workday",
      sequence: 10,
      childrenFrom: "QC_MODULES_WORKDAY"
    },
    {
      id: "testing",
      title: "Testing",
      sequence: 20,
      childrenFrom: "QC_MODULES"
    },
    {
      id: "reference",
      title: "Reference",
      sequence: 30,
      items: []
    },
    {
      id: "data",
      title: "Data",
      sequence: 40,
      items: []
    },
    {
      id: "settings",
      title: "Settings",
      sequence: 50,
      items: []
    }
  ]
};
